language: clojure
lein: lein2
env:
    global:
        - secure: "LIdxe11Fj1VbJxj5AH7qDUAWI+zTZhY7PMuuCsz5aC3aZMpDXNCAPG/J7uZC\n48a5KU0YSXumfIwBHXqJzE+mqaWenT3sweKBqxSoBYgKsvv10Oe9qYclpdsZ\nI1fvoKKTaYqBb8zBpvqhzBuLuUG4RKlGr4YXt5XuEmfUnQVW40I="

script:
    - lein test

after_script:
    - gem install heroku
    - git remote add heroku git@heroku.com:clojure-heroku-playground.git
    - echo "Host heroku.com" >> ~/.ssh/config
    - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
    - echo "   CheckHostIP no" >> ~/.ssh/config
    - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
    - heroku keys:clear
    - yes | heroku keys:add
    - yes | git push heroku master
